version: "3"
services:
  redis:
    image: elestio/redis:${SOFTWARE_VERSION_TAG}
    command: redis-server --save 10 1 --loglevel warning --requirepass ${SOFTWARE_PASSWORD}
    shm_size: "1g"
    env_file:
      - .env
    volumes:
      - ./data:/data
    restart: always
    ports:
      - "26379:6379"

  redisinsight:
    image: redislabs/redisinsight:latest
    restart: always
    user: 0:0
    environment:
      - RIPROXYENABLE=true
      - RITRUSTEDORIGINS=https://${DOMAIN}
    ports:
      - "172.17.0.1:8001:8001"
    volumes:
      - ./insight:/db
