version: '3'
services:
  redis:
    image: redis:${SOFTWARE_VERSION_TAG}
    command: redis-server --save 10 1 --loglevel warning --requirepass ${SOFTWARE_PASSWORD}
    shm_size: '1g'
    env_file:
      - .env
    volumes:
      - ./data:/data
    restart: always
    ports:
      - "172.17.0.1:6379:6379"

  redisinsight:
    image: redislabs/redisinsight:1.12.0
    restart: always
    user: 0:0
    ports:
      - '172.17.0.1:8001:8001'
    volumes:
      - ./insight:/db 